Change org name
hubverse-org/hubData pull request #42
Opened 2024-06-18 15:35 UTC by annakrystalli

Resolves #41

2024-06-18 21:17 UTC, lshandross requested changes

2024-06-18 21:17 UTC, lshandross commented on tests/testthat/_snaps/hub-connection.md
There are a couple more instances of the incorrect organization name in this file on lines 1025, 1031, and 1040

2024-06-18 21:17 UTC, lshandross commented on tests/_snaps/hub-connection.md
There are a couple more instances of the incorrect organization name in this file on lines 1025, 1031, and 1040

2024-06-19 06:30 UTC, annakrystalli commented on DESCRIPTION
I made a small edit but will leave it for now. Happy to revisit at a later date though if folks want to change it

2024-06-19 06:31 UTC, merged