Bsweger/skip data checks option
hubverse-org/hubData pull request #47
Opened 2024-07-09 03:10 UTC by bsweger

[In draft while tying up loose ends: better error message, NEWS, etc.]

Fixes #43

This PR adds a `skip_check` option to `hubData`'s `connect_hub` and `connect_model_output` functions.

Setting this option to TRUE means that calls to `arrow::open_dataset` will set `exclude_invalid_files` to FALSE (i.e., arrow won't read through all the files on S3 and toss out those of the wrong format).

Defaults (if `skip_check` is not specified by user):
  - `skip_check` will be set to TRUE if the hub's path is S3
  - otherwise, `skip_check` will be set to FALSE

2024-07-09 03:54 UTC, bsweger commented
@annakrystalli This isn't ready for a full review, but before going further, would love your thoughts on the direction of these changes.

[This question(S) turned out longer than I'd anticipated--maybe worth a synchronous chat?]

The new option to skip data checks has the performance impact we want: `connect_hub` against the FluSight archives was taking ~9 minutes to run on my laptop and now completes anywhere between 5 and 7 seconds.

```R
hub_path_cloud <- s3_bucket("uscdc-flusight-hub-v1")
# below will fail if we don't specify file_format, because the hub's valid formats 
# are parquet AND csv (because we're no longer validating file formats during open_dataset)
# https://github.com/hubverse-org/flusight_hub_archive/blob/main/hub-config/admin.json#L10
hub_con <- connect_hub(hub_path_cloud, file_format = "parquet"))
```

That said, I don't love how the change introduces different default behavior for S3-based hubs. Should we:

1. force users of S3-based hubs to explicitly pass in `skip_checks = TRUE`, thereby retaining the default behavior of `skip_checks = FALSE` regardless of hub location? OR
2. accept that cloud based hubs have different needs and favor doing the "right" thing by default?

If we accept the second statement, it doesn't really make sense that we set `skip_checks` to TRUE on behalf of S3 users, but we don't set `file_format` to parquet, when both parameters are necessary most of the time. I feel okay about the skip_checks default, but I don't think we should make an assumption that every S3-based hub will contain parquet files only.

Given the above (and considering the possibility that our arrow options for cloud-based hubs may diverge even further from the local options as we learn more), does it make sense to try using DuckDB instead of arrow in `connect_hub.SubTreeFileSystem` (or file an issue to do that later) 
 * sidestep `skip_checks` and prevent us from handling S3 different that other cloud file systems
 * but may introduce new classes of errors and edge cases

2024-07-09 10:57 UTC, annakrystalli commented
Just to note,I have not looked at the code yet so this is a more high level response.

I totally agree with you on all your areas and degrees of hesitation.

Personally I feel it's worse for the default settings to return an error than be slow and I definitely don't feel the default of S3 hub connections should be to assume the hub is a hubverse transformed hub and therefore set the format to parquet by default.

Given the above I almost feel like we should not have different defaults for local Vs S3 but instead issue a performance warning with more (or links to more) information about skipping certain checks and their implications/expectations.

This is also making me feel even more strongly that the very special situation of a hubverse cloud transformed hub should be able to be detected/communicated and override defaults. 
I continue to think a special file might be the way to go. It is certainly common in R (e.g. .Rproj files, _pkgdown files etc), am pretty sure it is in python too and could also act as a location for further hubverse transform configurations (e.g. partitions etc)

2024-07-09 10:58 UTC, annakrystalli commented
Re duckdb I am definitely curious and open to exploring that as the default!

2024-07-09 11:43 UTC, annakrystalli commented
One last thought. If not a special file, perhaps a dedicated function for specifically accessing hubverse transformed cloud hubs with appropriate defaults might work?

2024-07-09 14:01 UTC, bsweger commented
> One last thought. If not a special file, perhaps a dedicated function for specifically accessing hubverse transformed cloud hubs with appropriate defaults might work?

Thanks for weighing in--we're in agreement that this PR as written is not the way to go for solving our performance issues on cloud-based data.

I'm not clear on what you mean by a "special file." Can you say more about that?

I think trying DuckDB is a worthy experiment: the performance limitations we're hitting with `connect_hub` aren't related to partitioning or other physical storage strategies. We seem to be hitting Arrow-related limitations since we can't even get a lazy table object open without S3-related performance issues.

For example, I tried passing in a specific list of S3 URIs (instead of the model-output directory) to `open_dataset`, in hopes that Arrow could open the correct files w/o needing to scan the entire S3 contents via `exclude_invalid_files = TRUE`. 

That strategy was not successful ([branch here](https://github.com/bsweger/hubData/tree/bsweger-test/open_dataset_uri)), seemingly because Arrow's R implementation will make an S3 call for every file in the list: https://github.com/apache/arrow/issues/35715 (this issue was filed by a friend of yours 😄 ).

If DuckDB can provide a consistent interface for all cloud-based hubs, regardless of where they are hosted or what the file format is, my .02 is that would be preferable to options that require a special handling for Hubverse-hosted connections.

2024-07-09 14:15 UTC, annakrystalli commented
> I'm not clear on what you mean by a "special file." Can you say more about that?

I was referring tp the suggestion I had made in this issue: https://github.com/hubverse-org/hubData/issues/37#issuecomment-2166683195
i.e.
> It would be nicer however for the function to be able to detect that it's dealing with a cloud hub were the above conditions are guaranteed and set those checks to off by default in that case. Perhaps through including a `.cloud-hub` file in the root of the hub that the function could use to detect such a hub?


> That strategy was not successful ([branch here](https://github.com/bsweger/hubData/tree/bsweger-test/open_dataset_uri)), seemingly because Arrow's R implementation will make an S3 call for every file in the list: [apache/arrow#35715](https://github.com/apache/arrow/issues/35715) (this issue was filed by a friend of yours 😄 ).

 😜 yeah I thinks I experimented with that initially and then abandoned it...


> If DuckDB can provide a consistent interface for all cloud-based hubs, regardless of where they are hosted or what the file format is, my .02 is that would be preferable to options that require a special handling for Hubverse-hosted connections.


💯 I've always felt collecting everything into some sort of database is the right and most robust approach and should be an option in the hubverse ecosystem so also agree that trying DuckDB is a worthy experiment!

2024-07-17 20:42 UTC, bsweger commented
@annakrystalli Been thinking about this some more. @matthewcornell and I are continuing to explore DuckDB for consuming data from a cloud-based hub.

What we learn will likely be relevant to potentially using DuckDB in `hubData`, but in the meantime, what do you think about solving the immediate pain by returning to the "skip data checks" idea, just implemented differently than this current PR?

Agree with your statement that defaults shouldn't cause errors. So what if we add "skip checks" but never make it the default? That way we have an option that will allow people to connect to something like the flusight archives, even if they have to be explicit.

2024-07-18 00:48 UTC, annakrystalli commented
Yes agree that's the easiest effective way forward.

Also what do you think about this suggestion?
> Given the above I almost feel like we should not have different defaults for local Vs S3 but instead issue a performance warning on cloud with more (or links to more) information about skipping certain checks and their implications/expectations.

Is it weird to issue a message by default when connecting to cloud?

2024-07-18 10:20 UTC, annakrystalli commented
BTW when your ready for an actual code review just let me know!

2024-07-19 18:52 UTC, bsweger commented
@annakrystalli PR is ready for review!

> Is it weird to issue a message by default when connecting to cloud?

A message like that would probably help people, but I wasn't sure where to put it. After `connect_hub`/`connect_model_output` is too late. We could preemptively display a message about `skip_checks` after someone creates an `s3_bucket` object? 

Happy to update this PR, but if we don't have a good idea/wording in the short-term, I'd suggest merging this and revisiting later.

2024-07-19 19:10 UTC, bsweger commented on R/utils-connect_hub.R
> +check_file_format <- function(model_output_dir, file_format, skip_checks,
I'd originally hoped to skip this function with the `skip_checks` parameter is `TRUE`. In my testing against the FluSight archive hub, doing so eliminated ~3 more seconds from the connection time.

However, advantage of keeping this check is being able to abort with a useful message if someone tries using `skip_checks` with a hub that has multiple types of files in the model output directory.

2024-07-24 14:23 UTC, annakrystalli requested changes
This all looks pretty good to me, just some minor change requests.

I think it would also be good to have a short section in the `connect_hub` vignette about this also: https://github.com/hubverse-org/hubData/blob/main/vignettes/articles/connect_hub.Rmd

2024-07-24 14:23 UTC, annakrystalli commented on R/connect_hub.R
> +    format_verified = exclude_invalid_files_flag,
Nice idea to include this as a hub attribute. Can we call the attribute `checks` so that it ties in more intuitively with the name of the argument (`skip_checks`) that determines its values?

2024-07-24 15:03 UTC, annakrystalli commented
One last comment. We generally also need to bump the version in the `DESCRIPTION` file, although given I'm going to be merging in after #49 , I can take care of that after if you like when I resolve the merge conflicts.

2024-07-25 13:50 UTC, bsweger commented
@annakrystalli Thanks for the review--I pushed updates to address the requested changes, so it's ready for another look!

2024-07-25 14:23 UTC, annakrystalli commented on vignettes/articles/connect_hub.Rmd
> +```
This is great. I do wonder whether there should be a header for the section to bring attention to the topic (it'll appear in the TOC too) and also an introductory sentence to warn folks that the default behaviour of running these checks can be extremely slow on very large hubs?

2024-07-25 20:08 UTC, annakrystalli approved these changes

2024-07-26 05:49 UTC, merged